### ISSUE TITLE
Review mypy config

### ISSUE THREAD

**Issue by ruestefa** [MeteoSwiss-APN/mch-python-blueprint#82]
Mypy is currently mostly unconfigured:

```toml
# tmpl/pyproject.toml.j2

[tool.mypy]

[[tool.mypy.overrides]]
module = [
    # Add external modules w/o type hints here
]
ignore_missing_imports = true
```

By contrast, in my own template (which I'm now in the process of migrating to the blueprint), it is configured comparatively extensively:

```ini
# mypy.ini

[mypy]
# --strict options (v0.941)
check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
# disallow_untyped_calls = True
# disallow_untyped_decorators = True
disallow_untyped_defs = True
no_implicit_optional = True
no_implicit_reexport = True
strict_equality = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True

# ...
```

I'm not sure whether I've added this configuration after branching from the original (cookiecutter-based) blueprint, or whether it's somehow gone lost during refactoring and the migration to copier (though a quick look at the git history suggests the former). Either way, though, at least some of the options should be added to the default configuration provided by the blueprint (see, e.g., this [blog post](https://blog.wolt.com/engineering/2021/09/30/professional-grade-mypy-configuration/) I've stumbled over that explains some relevant options and the need for them).

Once I've reviewed my own mypy config, I'll post it here as a suggestion.
